changelog:
  exclude:
    labels: [skip-changelog]
  categories:
    - title: Research and reporting improvements
      labels: [enhancement, feature]
    - title: Fixes
      labels: [bug, fix]
    - title: Documentation
      labels: [documentation]
    - title: Dependencies and maintenance
      labels: [dependencies, maintenance]
    - title: Other changes
      labels: ["*"]
